---
- name: "Apache installation using docker"
  hosts: prod
  become: true
  vars_files:
    - files/secrets/credentials.yml
  pre_tasks:
    - name: Install EPEL repo
      package: name=epel-release state=present
      when: ansible_distribution == "CentOS"
    - name: install python3-pip
      yum: name=python3-pip state=present update_cache=yes
    - name: Install docker python3
      pip: name=docker
  tasks:
    - name: "Configuring yum repository for Docker"
      yum_repository:
        name: "docker"
        description: "docker repo"
        gpgcheck: no
        baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
        
    - name: "Installing the Docker"
      command: "yum install docker-ce --nobest -y"
     
    - name: "Strating Docker Services..."
      service:
        name: "docker"
        state: started
        
    - name: Create Apache container
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
   
