---
- name: "Apache installation using docker"
  hosts: prod
  become: true
  vars_files:
    - files/secrets/credentials.yml
  pre_tasks:
    - name: Install EPEL repo
      package: name=epel-release state=present
      when: ansible_distribution == "CentOS"
    - name: install python3-pip
      yum: name=python3-pip state=present update_cache=yes
    - name: Install docker python3
      pip: name=docker
  tasks:
    - name: "pull httpd image"
      docker_image:
        name: httpd
        state: present
   
